### ISSUE TITLE
 mean_distances_from_alignments.py

### ISSUE THREAD

**Issue by Victaphanta** [mgharvey/misc_python#1]
Hi, Constantly getting the error when I try to run  mean_distances_from_alignments.py.

All my dependency biopython numpy are fine, not sure alignIO is misbehaving.  Hope you can help.

Adnan

jc_distances.txt is empty
jc_std.txt is empty
Traceback (most recent call last):
  File "MeanPairwise_pjc_distance.py", line 204, in <module>
    main()
  File "MeanPairwise_pjc_distance.py", line 142, in main
    args.format.lower())
  File "C:\Python27\lib\site-packages\Bio\AlignIO__init__.py", line 431, in read
    raise ValueError("No records found in handle")
ValueError: No records found in handle​

**Comment by mgharvey** [comment]
You have a file in the input folder that is not an alignment "MeanPairwise_pjc_distance.py". Remove that from the folder and it should work.

Mike
